title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://theoldworldguy.github.io/theoldworldguy
aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/theoldworldguy/theoldworldguy
